[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SOCKET_SERVER_URL = "https://dainty-shortbread-7cd23d.netlify.app"

[[redirects]]
  from = "/api/socket/*"
  to = "/.netlify/functions/socket"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"


